name: Continuous Integration

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Check format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  build:
    name: Build
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            deps: sudo apt-get update && sudo apt-get install -y libglib2.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config
          - os: windows-latest
            platform: windows
            deps: choco install pkgconfiglite
          - os: macos-latest
            platform: macos
            deps: brew install pkg-config
            
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: ${{ matrix.deps }}
      shell: bash
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        shared-key: "rust-rcp-client-${{ matrix.platform }}"
        cache-on-failure: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    
    # Save compiled artifacts for release workflow
    - name: Cache artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/cache@v3
      with:
        path: target
        key: rust-rcp-client-${{ matrix.platform }}-${{ github.sha }}
        restore-keys: |
          rust-rcp-client-${{ matrix.platform }}-
